name: ci_tests

on:
  pull_request:
    branches:
    - master
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: dependencies
      - run: npm i
      - run: npm run lint
      - run: npm run test

